CREATE DATABASE BANCOSESSAOORIGINAL;

CREATE TABLE BANCOSESSAOORIGINAL.ENDERECO(

IDENDERECO INT NOT NULL AUTO_INCREMENT,
RUA 		VARCHAR(255) NOT NULL,
NUMERO 		VARCHAR(255) NOT NULL,
COMPLEMENTO VARCHAR(100) NOT NULL,
BAIRRO 		VARCHAR(100) NOT NULL,
CIDADE 		VARCHAR(100) NOT NULL,
CONSTRAINT PK_ENDERECO PRIMARY KEY (IDENDERECO)

);

CREATE TABLE BANCOSESSAOORIGINAL.CLIENTE(
ID 			INT NOT NULL AUTO_INCREMENT,
NOME 		VARCHAR(100) NOT NULL,
RG 			DOUBLE NOT NULL,
CPF 		DOUBLE NOT NULL,
ENDERECO 	INT NOT NULL,
CONSTRAINT PK_CLIENTE PRIMARY KEY (ID),
CONSTRAINT FK_ENDERECOCLIENTE FOREIGN KEY (ENDERECO) REFERENCES BANCOSESSAOORIGINAL.ENDERECO(IDENDERECO)
);

CREATE TABLE BANCOSESSAOORIGINAL.CONTA (
IDCLIENTE INT NOT NULL,
IDCONTA INT NOT NULL AUTO_INCREMENT,
NUMCONTA INT NOT NULL,
NUMAGENCIA INT NOT NULL,
CONSTRAINT PK_CLIENTE PRIMARY KEY (IDCONTA),
CONSTRAINT FK_CLIENTE FOREIGN KEY (IDCLIENTE) REFERENCES BANCOSESSAOORIGINAL.CLIENTE(ID)

)








